# coding: utf-8

"""
    predictor_scoring

    Credit Score Predictor  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.renew_token_request import RenewTokenRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestRenewTokenRequest(unittest.TestCase):
    """RenewTokenRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRenewTokenRequest(self):
        """Test RenewTokenRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.renew_token_request.RenewTokenRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
