# coding: utf-8

"""
    predictor_scoring

    Credit Score Predictor  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.start_batch_execution_response import StartBatchExecutionResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestStartBatchExecutionResponse(unittest.TestCase):
    """StartBatchExecutionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStartBatchExecutionResponse(self):
        """Test StartBatchExecutionResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.start_batch_execution_response.StartBatchExecutionResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
